import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';





export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lucy de Rojas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lucy de Rojas</h1>
      <p>Para here</p>
      <Link href="/page2"><a>Page 2</a></Link>

      

    </div>
  )
}
